name: branch-deploy

on:
  issue_comment:
    types: [ created ]

permissions:
  id-token: write
  pull-requests: write
  deployments: write
  contents: write
  checks: read

env:
  WORKING_DIR: "./"

jobs:
  branch-deploy:
    name: "branch deploy"
    if: ${{ github.event.issue.pull_request }} # only run on pull request comments
    runs-on: ubuntu-latest
    environment: production # only used to aquire secrets
    # defaults:
    #   run:
    #     working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: branch-deploy
        id: branch-deploy
        uses: github/branch-deploy@v5.0.0
        with:
          environment_targets: "production"

      - name: checkout
        uses: actions/checkout@v3.3.0
        if: ${{ steps.branch-deploy.outputs.continue == 'true' }}
        with:
          ref: ${{ steps.branch-deploy.outputs.ref }}

      - name: azure-login
        uses: azure/login@v1
        if: ${{ steps.branch-deploy.outputs.continue == 'true' }}
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # .deploy noop logic
      - name: Bicep what-if
        if: ${{ steps.branch-deploy.outputs.continue == 'true' &&
          steps.branch-deploy.outputs.noop == 'true' }}
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: eastus
          template: ./main.bicep
          additionalArguments:  --what-if

      # .deploy logic
      - name: Bicep deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' &&
          steps.branch-deploy.outputs.noop != 'true' }}
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: eastus
          template: ./main.bicep